### PR TITLE
feature: migrate to Flutter 3.16

### PR DESCRIPTION
**Pull request by amrgetment**
I migrated to Flutter 3.16

PaintingBinding.instance.instantiateImageCodec is removed from 3.16
https://docs.flutter.dev/release/breaking-changes/3-13-deprecations#updates-to-imageprovider-and-paintingbinding

I fixed loading on Chrome by using the http library's client instead of the dart:io client it was giving the following error
`Error: Unsupported operation: Platform._version`

### CODE REVIEW

**Comment by amrgetment** [comment]
@pierluigizagaria Could you review and publish a new version to support Flutter 3.16

**Comment by pierluigizagaria** [comment]
Thank you for the contribution!

**Comment by amrgetment** [comment]
@pierluigizagaria Using fixed HTTP version causes issues

```

Because no versions of dart_code_linter match >1.1.1 <2.0.0 and dart_code_linter 1.1.1 depends on http ^0.13.5, dart_code_linter ^1.1.1 requires http ^0.13.5.
And because gif >=2.3.0 depends on http ^1.1.0, dart_code_linter ^1.1.1 is incompatible with gif >=2.3.0.
So, because ment depends on both gif ^2.3.0 and dart_code_linter ^1.1.1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on gif: flutter pub add gif:^2.2.0
exit code 1
```
I have to override it

```
dependency_overrides:
  http: ^1.1.0
```

**Comment by pierluigizagaria** [comment]
I'll leave the fixed version because the problem seems to be dependent from `dart_code_linter`

In one of the [latest commit ](https://github.com/bancolombia/dart-code-linter/commit/0ddf882d9166ee9ec90939d58bee75056fa1ee30)they updated the minimum version of http to 1.1.0

Just wait for their update and the issue will go away.

**Pull request merged**
